language: node_js
node_js:
  - 12


dist: bionic

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s --
  - export PATH="$HOME/.yarn/bin:$PATH"


before_script:
  - yarn --frozen-lockfile

script: yarn run test

